repos:
  - repo: local
    hooks:
      - id: clang-format
        stages: [commit, push]
        name: Clang format
        entry: clang-format -i -style=file
        language: system
        types: [file]
        files: \.(c|cpp|h|hpp)$
