# This is a basic workflow to help you get started with Actions

name: Clang Format

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          # check out HEAD on the branch
        ref: ${{ github.head_ref }}
          # make sure the parent commit is grabbed as well, because
          # that's what will get formatted (i.e. the most recent commit)
        fetch-depth: 2
    - name: Format
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './src'       
        clangFormatVersion: 11
        inplace: True
    - name: Commit
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: '🎨 Committing clang-format changes'
        branch: ${{ github.head_ref }}
